apiVersion: v1
kind: Service
metadata:
  labels:
    application: producer
  name: producer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: producer
  sessionAffinity: None
  type: ClusterIP
