# Spring Boot
spring:
  banner:
    location: banner.txt

client-keystore:
  location: /Users/pitta/Workspace/git/amq-demo/amq7-broker-tls-sni-demo/tls/client.ks
  password: password

client-truststore:
  location: /Users/pitta/Workspace/git/amq-demo/amq7-broker-tls-sni-demo/tls/client.ts
  password: password


amq-broker:
  url: broker-amq-demo.example.com
  #url: broker-amq-demo.apps.cluster-0df2.0df2.example.opentlc.com
  port: 443
  options: jms.username=amquser&jms.password=password&transport.keyStoreLocation=${client-keystore.location}&transport.keyStorePassword=${client-keystore.password}&transport.trustStoreLocation=${client-truststore.location}&transport.trustStorePassword=${client-truststore.password}&transport.verifyHost=false

amqp:
  destination:
    name: demoQueue

# AMQPHub
amqphub:
  amqp10jms:
    pool:
      enabled: true
    remote-url: amqps://${amq-broker.url}:${amq-broker.port}?${amq-broker.options}
    #username: admin
    #password: admin

# Camel Spring Boot
camel:
  springboot:
    name: amqp-console-producer
    main-run-controller: true

# Logging
logging:
  level:
    root: ERROR
    #org.apache.camel.examples: DEBUG
