apiVersion: v1
kind: Secret
metadata:
  name: broker-params
type: Opaque 
stringData:
  amq-broker.url: broker-amq-demo.apps.cluster-0df2.0df2.example.opentlc.com
  client-truststore.location: /appdata/config/client.ts
  client-truststore.password: password
  client-keystore.location: /appdata/config/client.ks
  client-keystore.password: password
  amqphub.amqp10jms.username: amquser
  amqphub.amqp10jms.password: password
