apiVersion: v1
kind: Service
metadata:
  labels:
    application: consumer
  name: consumer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: consumer
  sessionAffinity: None
  type: ClusterIP
