apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: consumer
  name: consumer
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: consumer:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: clients/cli-amqp-consumer
    git:
      ref: main
      uri: https://github.com/pittar/amq7-broker-tls-sni-demo
    type: Git
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: java:8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
